version: '3'

services:
 backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - env
    ports:
      - "8000:8000"
    volumes:
      - ./django_backend:/app/backend
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - main
    depends_on:
      - db

 db:
   image: postgres
   ports:
     - "5432:5432"
   env_file:
     - env
   volumes:
     - postgres_data:/var/lib/postgresql/data
   networks:
     - main


 frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs_frontend:/app/frontend
    command: npm run dev
    depends_on:
      - backend
    networks:
      - main

networks:
 main:
   driver: bridge

volumes:
  postgres_data: