version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - env
    ports:
      - "8000:8000"
    volumes:
      - ./django_backend:/app/backend
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react_frontend:/app/frontend
    command: npm start
    depends_on:
      - backend
