# Use the official Node.js image as a base
FROM node:21

# Set environment variables
ENV NODE_ENV=development

# Set the working directory
WORKDIR /app/nextjs_frontend/frontend

# Copy the frontend code into the container
COPY nextjs_frontend/frontend .

# Install dependencies
RUN npm install

# Expose port 3000 to allow communication to/from the React application
EXPOSE 3000

# Command to start the React development server
CMD ["npm", "run", "dev"]
